service: es-strata-sg
provider:
  name: aws
  deploymentBucket:
    name: com.serverless.${self:provider.region}.deploys
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  memorySize: 512
  timeout: 10
  tracing:
    lambda: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  strata-period-wrangler:
    name: es-strata-period-wrangler
    handler: strata_period_wrangler.lambda_handler
    package:
      include:
        - strata_period_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      checkpoint: 2
      bucket_name: results-s3-bucket
      in_file_name: enrichment_out.json
      incoming_message_group: enrichment-out
      method_name: es-strata-method
      out_file_name: strata_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: strata-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  strata-period-method:
    name: es-strata-method
    handler: strata_period_method.lambda_handler
    package:
      include:
        - strata_period_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      strata_column: strata
      value_column: Q608_total
